name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: "read"
      actions: "read"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jameshenry/publish-shell-action@v1
        with:
          github-token: ${{ secrets.ENG_GITHUB_TOKEN }}
