name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      checks: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jameshenry/publish-shell-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
